+++

diff --git a/STM32_PROJECTS/Beginning_STM32_book/libopencm3/Makefile b/STM32_PROJECTS/Beginning_STM32_book/libopencm3/Makefile
--- a/STM32_PROJECTS/Beginning_STM32_book/libopencm3/Makefile
+++ b/STM32_PROJECTS/Beginning_STM32_book/libopencm3/Makefile
@@ -17,24 +17,26 @@
 ## along with this library.  If not, see <http://www.gnu.org/licenses/>.
 ##
 
-PREFIX		?= arm-none-eabi
-#PREFIX		?= arm-elf
+PREFIX		?= arm-none-eabi-
 
 STYLECHECK      := scripts/checkpatch.pl
 STYLECHECKFLAGS := --no-tree -f --terse --mailback
 
-space:=
-space+=
-SRCLIBDIR:= $(subst $(space),\$(space),$(realpath lib))
-
-TARGETS := stm32/f0 stm32/f1 stm32/f2 stm32/f3 stm32/f4 stm32/f7
-TARGETS += stm32/l0 stm32/l1 stm32/l4
-TARGETS += lpc13xx lpc17xx lpc43xx/m4 lpc43xx/m0
-TARGETS += lm3s lm4f
-TARGETS += efm32/tg efm32/g efm32/lg efm32/gg
-TARGETS += sam/3a sam/3n sam/3s sam/3u sam/3x
-TARGETS += sam/d
-TARGETS += vf6xx
+TARGETS ?=	stm32/f0 stm32/f1 stm32/f2 stm32/f3 stm32/f4 stm32/f7 \
+		stm32/l0 stm32/l1 stm32/l4 \
+		stm32/g0 stm32/g4 \
+		stm32/h7 \
+		gd32/f1x0 \
+		lpc13xx lpc17xx lpc43xx/m4 lpc43xx/m0 \
+		lm3s lm4f msp432/e4 \
+		efm32/tg efm32/g efm32/lg efm32/gg efm32/hg efm32/wg \
+		efm32/ezr32wg \
+		nrf/51 nrf/52 \
+		sam/3a sam/3n sam/3s sam/3u sam/3x sam/4l \
+		sam/d \
+		vf6xx \
+		swm050 \
+		pac55xx
 
 # Be silent per default, but 'make V=1' will show all compiler calls.
 ifneq ($(V),1)
@@ -44,8 +46,11 @@ MAKEFLAGS += --no-print-directory
 endif
 
 # Avoid the use of shell find, for windows compatibility
-IRQ_DEFN_FILES	:= $(wildcard include/libopencm3/*/irq.json)
-IRQ_DEFN_FILES	+= $(wildcard include/libopencm3/*/*/irq.json)
+IRQ_DEFN_FILES  := $(foreach TARGET,$(TARGETS),$(wildcard include/libopencm3/$(TARGET)/irq.json))
+NVIC_H := $(IRQ_DEFN_FILES:%/irq.json=%/nvic.h)
+VECTOR_NVIC_C := $(IRQ_DEFN_FILES:./include/libopencm3/%/irq.json=./lib/%/vector_nvic.c)
+IRQHANDLERS_H := $(IRQ_DEFN_FILES:./include/libopencm3/%/irq.json=./include/libopencmsis/%/irqhandlers.h)
+IRQ_GENERATED_FILES = $(NVIC_H) $(VECTOR_NVIC_C) $(IRQHANDLERS_H)
 STYLECHECKFILES := $(wildcard include/*/*.h include/*/*/*.h include/*/*/*/*.h)
 STYLECHECKFILES += $(wildcard lib/*/*.h lib/*/*/*.h lib/*/*/*/*.h)
 STYLECHECKFILES += $(wildcard lib/*/*.c lib/*/*/*.c lib/*/*/*/*.c)
@@ -54,32 +59,39 @@ all: build
 
 build: lib
 
-%.genhdr:
+include/libopencm3/%/nvic.h lib/%/vector_nvic.c include/libopencmsis/%/irqhandlers.h: include/libopencm3/%/irq.json ./scripts/irq2nvic_h
 	@printf "  GENHDR  $*\n";
-	@./scripts/irq2nvic_h ./$*;
+	$(Q)./scripts/irq2nvic_h ./$<;
 
 %.cleanhdr:
 	@printf "  CLNHDR  $*\n";
-	@./scripts/irq2nvic_h --remove ./$*
+	$(Q)./scripts/irq2nvic_h --remove ./$*
 
 LIB_DIRS:=$(wildcard $(addprefix lib/,$(TARGETS)))
-$(LIB_DIRS): $(IRQ_DEFN_FILES:=.genhdr)
+$(LIB_DIRS): $(IRQ_GENERATED_FILES)
+	$(Q)$(RM) .stamp_failure_$(subst /,_,$@)
 	@printf "  BUILD   $@\n";
-	$(Q)$(MAKE) --directory=$@ SRCLIBDIR="$(SRCLIBDIR)"
+	$(Q)$(MAKE) --directory=$@ PREFIX="$(PREFIX)" || \
+		echo "Failure building: $@: code: $$?" > .stamp_failure_$(subst /,_,$@)
 
 lib: $(LIB_DIRS)
-	$(Q)true
+	$(Q)$(RM) .stamp_failure_tld
+	$(Q)for failure in .stamp_failure_*; do \
+		[ -f $$failure ] && cat $$failure >> .stamp_failure_tld || true; \
+	done;
+	$(Q)[ -f .stamp_failure_tld ] && cat .stamp_failure_tld && exit 1 || true;
 
 html doc:
-	$(Q)$(MAKE) -C doc html
+	$(Q)$(MAKE) -C doc html TARGETS="$(TARGETS)"
 
-clean: $(IRQ_DEFN_FILES:=.cleanhdr) $(LIB_DIRS:=.clean) $(EXAMPLE_DIRS:=.clean) doc.clean styleclean
+clean: $(IRQ_DEFN_FILES:=.cleanhdr) $(LIB_DIRS:=.clean) $(EXAMPLE_DIRS:=.clean) doc.clean styleclean genlinktests.clean
 
 %.clean:
 	$(Q)if [ -d $* ]; then \
 		printf "  CLEAN   $*\n"; \
-		$(MAKE) -C $* clean SRCLIBDIR="$(SRCLIBDIR)" || exit $?; \
+		$(MAKE) -C $* clean || exit $?; \
 	fi;
+	$(Q)$(RM) .stamp_failure_*;
 
 
 stylecheck: $(STYLECHECKFILES:=.stylecheck)
@@ -103,6 +115,8 @@ styleclean: $(STYLECHECKFILES:=.styleclean)
 LDTESTS		:=$(wildcard ld/tests/*.data)
 
 genlinktests: $(LDTESTS:.data=.ldtest)
+genlinktests.clean:
+	$(Q)rm -f $(LDTESTS:.data=.out)
 
 %.ldtest:
 	@if ./scripts/genlinktest.sh $* >/dev/null; then\
@@ -111,5 +125,7 @@ genlinktests: $(LDTESTS:.data=.ldtest)
 		printf "  TEST FAIL : $*\n";		\
 	fi;
 
+list-targets:
+	@echo $(TARGETS)
 
-.PHONY: build lib $(LIB_DIRS) doc clean generatedheaders cleanheaders stylecheck genlinktests
+.PHONY: build lib $(LIB_DIRS) doc clean generatedheaders cleanheaders stylecheck genlinktests genlinktests.clean list-targets
